FROM danforthcenter/plantcv
#@sha256:ff4b72258f4351e9523058879dac2a2655afe78491951f3f5c3f0c61c981c74a

RUN pip install cppcpyutils

COPY ./plantcv.Makefile /home/jovyan/work/Makefile
COPY ./renderRmd.r /home/jovyan/work/
